### ISSUE TITLE
Remove onCancelled event option

### ISSUE THREAD

**Issue by Exocomp** [conradreuter/cancellationtoken#17]
Example:

```
token.onCancelled(myFunction)
...
// do work
...
// Ex:
token.removeAllCancelled()
```

Use case:

A singleton service which calls cancel() first (if exists) and then creates a new token and dispatches work in another singleton service. The expectation is if token.onCancelled is registered it triggers. However, if work completes it can remove onCancelled so it never gets called since there is no need for it anymore.

**Comment by AArnott** [comment]
A `removeAllCancelled` method would allow causing unexpected side effects leading to malfunction elsewhere. If other code had registered callbacks, we wouldn't want your example code above to remove those other callbacks as they may still be needed.

Instead, consider the recommended pattern is to remove only the callback you added, via the return value of the `onCancelled` function:

https://github.com/conradreuter/cancellationtoken/blob/f272405c99ed5dd38e585f6f32c59b1da32b8663/src/CancellationToken.ts#L74-L79

I recommend we close the issue.

**Comment by conradreuter** [comment]
> I recommend we close the issue.

Agreed.
