### ISSUE TITLE
Stop the timeout without cancelling

### ISSUE THREAD

**Issue by reuzel** [conradreuter/cancellationtoken#9]
Hi,

First of all, great library.

When looking at this (and other) libraries that provide cancellation through timeout, is that I wish to stop the cancellation from occurring when my process ended before the timeout occurred. In .NET, the disposal of the CancellationTokenSource takes care of that. I think this library would benefit also from such a dispose function. Such a disposal would disallow a token to be cancelled, remove any timer, and cleanup any callback registrations. 

Your thoughts?

Joost

**Comment by AArnott** [comment]
I think what you're asking for is perfectly reasonable. @conradreuter ?

**Comment by conradreuter** [comment]
Can you provide a minimum example of how that would look like?

I want to see whether and how that could be achieved with what the library provides today, and if so, have a discussion on whether adding new functionality is worth it or not.

**Comment by reuzel** [comment]
Created a pull request with the necessary changes... #10

**Comment by MatthewLymer** [comment]
Sorry to revive a dead pull-request, but this functionality is pretty useful for me, @reuzel do you have this hosted on npm?

**Comment by AArnott** [comment]
It's a shame a fork may result. @conradreuter are you interested in transferring ownership of this repo and the NPM package to me to take forward?

**Comment by conradreuter** [comment]
@AArnott Agreed.

I provided an implementation and published a release candidate.

Feel free to reopen if something is missing. (:
